name: passcode_screen
version: 2.0.0+local
description: Local minimal replacement for passcode_screen.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
